name: Fix PHP code style issues

on:
  push:
    paths:
      - '**.php'
      - 'pint.json'
  pull_request:
    paths:
      - '**.php'
      - 'pint.json'

permissions:
  contents: read

jobs:
  php-code-styling:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Check PHP code style
        uses: aglipanci/laravel-pint-action@2.6
        with:
          configPath: pint.json
          testMode: true
          verboseMode: true
